name: "Add Issue Labels"
on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  triage:
    permissions:
      contents: read  # for github/issue-labeler to get repo contents
      issues: write  # for github/issue-labeler to create or remove labels
    runs-on: ubuntu-latest
    steps:
      # Update .github/labeler.yml for new dialects
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: github/issue-labeler@v3.2
        with:
          configuration-path: .github/labeler.yml
          include-title: 1
          include-body: 0
          not-before: 2023-07-06T02:54:32Z
          enable-versioned-regex: 0
          repo-token: ${{ github.token }}
