#
# This updates the current draft release notes when a PR is merged
#
name: Add to Release Notes
on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  draft-release:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    if: github.repository == 'sqlfluff/sqlfluff'
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit

    - name: Update release notes
      uses: release-drafter/release-drafter@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
