name: Publish dbt templater PyPI Version

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip tox

      - name: Build Distribution (dbt plugin)
        # tox commands run relative to the repo root.
        run: tox -e build-dist -- plugins/sqlfluff-templater-dbt

      - name: Copy builds to main dist folder
        # We move them here so that the github action can still access them
        run: cp -r plugins/sqlfluff-templater-dbt/dist/. dist/

      - name: Publish Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_DBT_TEMPLATER_TOKEN }}
          skip-existing: true
